version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: "api-gateway"
    ports:
      - "4004:4004"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # AUTH_SERVICE_URL: http://auth-service:4005
      AUTH_SERVICE_URL: http://host.docker.internal:4005
    restart: unless-stopped
    networks:
      - internal

networks:
  internal:
    external: true