FROM maven:3.9.9-eclipse-temurin-21 AS builder

# working directory
WORKDIR /app

# copy dependencies to the container working directory
COPY pom.xml .

# download dependencies, and cache with go-offline
RUN mvn dependency:go-offline -B

COPY src ./src

# build with new package
RUN mvn clean package

# next steps
FROM eclipse-temurin:21-jre AS runner

WORKDIR /app

COPY --from=builder ./app/target/billing-service-0.0.1-SNAPSHOT.jar ./app.jar

# port
EXPOSE 4001
EXPOSE 9001

# entrypoint
ENTRYPOINT ["java", "-jar", "./app.jar"]
